[custom]
overwrite_original_rules = true

update_ruleset_on_request = true

[[rulesets]]
group = "负载均衡"
ruleset = "[]FINAL"

[[custom_groups]]
name = "负载均衡"
type = "load-balance"
rule = [".*"]
interval = 1000000
strategy = "round-robin"
url = "http://www.gstatic.com/generate_204"
